// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/hsubbaraj/schedulator/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MockClusterAggregator is an autogenerated mock type for the ClusterAggregator type
type MockClusterAggregator struct {
	mock.Mock
}

type MockClusterAggregator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterAggregator) EXPECT() *MockClusterAggregator_Expecter {
	return &MockClusterAggregator_Expecter{mock: &_m.Mock}
}

// FullSync provides a mock function with given fields: ctx
func (_m *MockClusterAggregator) FullSync(ctx context.Context) ([]model.Cluster, []model.Replica, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FullSync")
	}

	var r0 []model.Cluster
	var r1 []model.Replica
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Cluster, []model.Replica, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Cluster); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Cluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []model.Replica); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]model.Replica)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClusterAggregator_FullSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullSync'
type MockClusterAggregator_FullSync_Call struct {
	*mock.Call
}

// FullSync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClusterAggregator_Expecter) FullSync(ctx interface{}) *MockClusterAggregator_FullSync_Call {
	return &MockClusterAggregator_FullSync_Call{Call: _e.mock.On("FullSync", ctx)}
}

func (_c *MockClusterAggregator_FullSync_Call) Run(run func(ctx context.Context)) *MockClusterAggregator_FullSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClusterAggregator_FullSync_Call) Return(_a0 []model.Cluster, _a1 []model.Replica, _a2 error) *MockClusterAggregator_FullSync_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClusterAggregator_FullSync_Call) RunAndReturn(run func(context.Context) ([]model.Cluster, []model.Replica, error)) *MockClusterAggregator_FullSync_Call {
	_c.Call.Return(run)
	return _c
}

// GetVLLMMetrics provides a mock function with given fields: ctx, appID
func (_m *MockClusterAggregator) GetVLLMMetrics(ctx context.Context, appID string) (model.VLLMMetrics, error) {
	ret := _m.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetVLLMMetrics")
	}

	var r0 model.VLLMMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.VLLMMetrics, error)); ok {
		return rf(ctx, appID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.VLLMMetrics); ok {
		r0 = rf(ctx, appID)
	} else {
		r0 = ret.Get(0).(model.VLLMMetrics)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterAggregator_GetVLLMMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVLLMMetrics'
type MockClusterAggregator_GetVLLMMetrics_Call struct {
	*mock.Call
}

// GetVLLMMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *MockClusterAggregator_Expecter) GetVLLMMetrics(ctx interface{}, appID interface{}) *MockClusterAggregator_GetVLLMMetrics_Call {
	return &MockClusterAggregator_GetVLLMMetrics_Call{Call: _e.mock.On("GetVLLMMetrics", ctx, appID)}
}

func (_c *MockClusterAggregator_GetVLLMMetrics_Call) Run(run func(ctx context.Context, appID string)) *MockClusterAggregator_GetVLLMMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterAggregator_GetVLLMMetrics_Call) Return(_a0 model.VLLMMetrics, _a1 error) *MockClusterAggregator_GetVLLMMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterAggregator_GetVLLMMetrics_Call) RunAndReturn(run func(context.Context, string) (model.VLLMMetrics, error)) *MockClusterAggregator_GetVLLMMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// WatchEvents provides a mock function with given fields: ctx
func (_m *MockClusterAggregator) WatchEvents(ctx context.Context) (<-chan model.ClusterEvent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WatchEvents")
	}

	var r0 <-chan model.ClusterEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan model.ClusterEvent, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan model.ClusterEvent); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.ClusterEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterAggregator_WatchEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchEvents'
type MockClusterAggregator_WatchEvents_Call struct {
	*mock.Call
}

// WatchEvents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClusterAggregator_Expecter) WatchEvents(ctx interface{}) *MockClusterAggregator_WatchEvents_Call {
	return &MockClusterAggregator_WatchEvents_Call{Call: _e.mock.On("WatchEvents", ctx)}
}

func (_c *MockClusterAggregator_WatchEvents_Call) Run(run func(ctx context.Context)) *MockClusterAggregator_WatchEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClusterAggregator_WatchEvents_Call) Return(_a0 <-chan model.ClusterEvent, _a1 error) *MockClusterAggregator_WatchEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterAggregator_WatchEvents_Call) RunAndReturn(run func(context.Context) (<-chan model.ClusterEvent, error)) *MockClusterAggregator_WatchEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClusterAggregator creates a new instance of MockClusterAggregator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterAggregator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterAggregator {
	mock := &MockClusterAggregator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
