// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockLeaderElector is an autogenerated mock type for the LeaderElector type
type MockLeaderElector struct {
	mock.Mock
}

type MockLeaderElector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLeaderElector) EXPECT() *MockLeaderElector_Expecter {
	return &MockLeaderElector_Expecter{mock: &_m.Mock}
}

// IsLeader provides a mock function with no fields
func (_m *MockLeaderElector) IsLeader() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsLeader")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockLeaderElector_IsLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLeader'
type MockLeaderElector_IsLeader_Call struct {
	*mock.Call
}

// IsLeader is a helper method to define mock.On call
func (_e *MockLeaderElector_Expecter) IsLeader() *MockLeaderElector_IsLeader_Call {
	return &MockLeaderElector_IsLeader_Call{Call: _e.mock.On("IsLeader")}
}

func (_c *MockLeaderElector_IsLeader_Call) Run(run func()) *MockLeaderElector_IsLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLeaderElector_IsLeader_Call) Return(_a0 bool) *MockLeaderElector_IsLeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderElector_IsLeader_Call) RunAndReturn(run func() bool) *MockLeaderElector_IsLeader_Call {
	_c.Call.Return(run)
	return _c
}

// OnElected provides a mock function with given fields: callback
func (_m *MockLeaderElector) OnElected(callback func()) {
	_m.Called(callback)
}

// MockLeaderElector_OnElected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnElected'
type MockLeaderElector_OnElected_Call struct {
	*mock.Call
}

// OnElected is a helper method to define mock.On call
//   - callback func()
func (_e *MockLeaderElector_Expecter) OnElected(callback interface{}) *MockLeaderElector_OnElected_Call {
	return &MockLeaderElector_OnElected_Call{Call: _e.mock.On("OnElected", callback)}
}

func (_c *MockLeaderElector_OnElected_Call) Run(run func(callback func())) *MockLeaderElector_OnElected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *MockLeaderElector_OnElected_Call) Return() *MockLeaderElector_OnElected_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLeaderElector_OnElected_Call) RunAndReturn(run func(func())) *MockLeaderElector_OnElected_Call {
	_c.Run(run)
	return _c
}

// OnLost provides a mock function with given fields: callback
func (_m *MockLeaderElector) OnLost(callback func()) {
	_m.Called(callback)
}

// MockLeaderElector_OnLost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnLost'
type MockLeaderElector_OnLost_Call struct {
	*mock.Call
}

// OnLost is a helper method to define mock.On call
//   - callback func()
func (_e *MockLeaderElector_Expecter) OnLost(callback interface{}) *MockLeaderElector_OnLost_Call {
	return &MockLeaderElector_OnLost_Call{Call: _e.mock.On("OnLost", callback)}
}

func (_c *MockLeaderElector_OnLost_Call) Run(run func(callback func())) *MockLeaderElector_OnLost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *MockLeaderElector_OnLost_Call) Return() *MockLeaderElector_OnLost_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLeaderElector_OnLost_Call) RunAndReturn(run func(func())) *MockLeaderElector_OnLost_Call {
	_c.Run(run)
	return _c
}

// NewMockLeaderElector creates a new instance of MockLeaderElector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLeaderElector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLeaderElector {
	mock := &MockLeaderElector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
