// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/hsubbaraj/schedulator/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MockPerformanceProfiler is an autogenerated mock type for the PerformanceProfiler type
type MockPerformanceProfiler struct {
	mock.Mock
}

type MockPerformanceProfiler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPerformanceProfiler) EXPECT() *MockPerformanceProfiler_Expecter {
	return &MockPerformanceProfiler_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function with given fields: ctx, appID
func (_m *MockPerformanceProfiler) GetProfile(ctx context.Context, appID string) (model.PerformanceProfile, error) {
	ret := _m.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 model.PerformanceProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PerformanceProfile, error)); ok {
		return rf(ctx, appID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PerformanceProfile); ok {
		r0 = rf(ctx, appID)
	} else {
		r0 = ret.Get(0).(model.PerformanceProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPerformanceProfiler_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockPerformanceProfiler_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *MockPerformanceProfiler_Expecter) GetProfile(ctx interface{}, appID interface{}) *MockPerformanceProfiler_GetProfile_Call {
	return &MockPerformanceProfiler_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, appID)}
}

func (_c *MockPerformanceProfiler_GetProfile_Call) Run(run func(ctx context.Context, appID string)) *MockPerformanceProfiler_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPerformanceProfiler_GetProfile_Call) Return(_a0 model.PerformanceProfile, _a1 error) *MockPerformanceProfiler_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPerformanceProfiler_GetProfile_Call) RunAndReturn(run func(context.Context, string) (model.PerformanceProfile, error)) *MockPerformanceProfiler_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPerformanceProfiler creates a new instance of MockPerformanceProfiler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPerformanceProfiler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPerformanceProfiler {
	mock := &MockPerformanceProfiler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
