// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/hsubbaraj/schedulator/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCacheRegistry is an autogenerated mock type for the CacheRegistry type
type MockCacheRegistry struct {
	mock.Mock
}

type MockCacheRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheRegistry) EXPECT() *MockCacheRegistry_Expecter {
	return &MockCacheRegistry_Expecter{mock: &_m.Mock}
}

// GetCacheLocations provides a mock function with given fields: ctx, modelID
func (_m *MockCacheRegistry) GetCacheLocations(ctx context.Context, modelID string) ([]model.CacheLocation, error) {
	ret := _m.Called(ctx, modelID)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheLocations")
	}

	var r0 []model.CacheLocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.CacheLocation, error)); ok {
		return rf(ctx, modelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.CacheLocation); ok {
		r0 = rf(ctx, modelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CacheLocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, modelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheRegistry_GetCacheLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheLocations'
type MockCacheRegistry_GetCacheLocations_Call struct {
	*mock.Call
}

// GetCacheLocations is a helper method to define mock.On call
//   - ctx context.Context
//   - modelID string
func (_e *MockCacheRegistry_Expecter) GetCacheLocations(ctx interface{}, modelID interface{}) *MockCacheRegistry_GetCacheLocations_Call {
	return &MockCacheRegistry_GetCacheLocations_Call{Call: _e.mock.On("GetCacheLocations", ctx, modelID)}
}

func (_c *MockCacheRegistry_GetCacheLocations_Call) Run(run func(ctx context.Context, modelID string)) *MockCacheRegistry_GetCacheLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheRegistry_GetCacheLocations_Call) Return(_a0 []model.CacheLocation, _a1 error) *MockCacheRegistry_GetCacheLocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheRegistry_GetCacheLocations_Call) RunAndReturn(run func(context.Context, string) ([]model.CacheLocation, error)) *MockCacheRegistry_GetCacheLocations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheRegistry creates a new instance of MockCacheRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheRegistry {
	mock := &MockCacheRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
