// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/hsubbaraj/schedulator/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// MockClusterClient is an autogenerated mock type for the ClusterClient type
type MockClusterClient struct {
	mock.Mock
}

type MockClusterClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterClient) EXPECT() *MockClusterClient_Expecter {
	return &MockClusterClient_Expecter{mock: &_m.Mock}
}

// CreateReplica provides a mock function with given fields: ctx, appID, constraints
func (_m *MockClusterClient) CreateReplica(ctx context.Context, appID string, constraints model.SchedulingConstraints) (string, error) {
	ret := _m.Called(ctx, appID, constraints)

	if len(ret) == 0 {
		panic("no return value specified for CreateReplica")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.SchedulingConstraints) (string, error)); ok {
		return rf(ctx, appID, constraints)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.SchedulingConstraints) string); ok {
		r0 = rf(ctx, appID, constraints)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.SchedulingConstraints) error); ok {
		r1 = rf(ctx, appID, constraints)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterClient_CreateReplica_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReplica'
type MockClusterClient_CreateReplica_Call struct {
	*mock.Call
}

// CreateReplica is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - constraints model.SchedulingConstraints
func (_e *MockClusterClient_Expecter) CreateReplica(ctx interface{}, appID interface{}, constraints interface{}) *MockClusterClient_CreateReplica_Call {
	return &MockClusterClient_CreateReplica_Call{Call: _e.mock.On("CreateReplica", ctx, appID, constraints)}
}

func (_c *MockClusterClient_CreateReplica_Call) Run(run func(ctx context.Context, appID string, constraints model.SchedulingConstraints)) *MockClusterClient_CreateReplica_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.SchedulingConstraints))
	})
	return _c
}

func (_c *MockClusterClient_CreateReplica_Call) Return(_a0 string, _a1 error) *MockClusterClient_CreateReplica_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterClient_CreateReplica_Call) RunAndReturn(run func(context.Context, string, model.SchedulingConstraints) (string, error)) *MockClusterClient_CreateReplica_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReplica provides a mock function with given fields: ctx, replicaID
func (_m *MockClusterClient) DeleteReplica(ctx context.Context, replicaID string) error {
	ret := _m.Called(ctx, replicaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReplica")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, replicaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterClient_DeleteReplica_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReplica'
type MockClusterClient_DeleteReplica_Call struct {
	*mock.Call
}

// DeleteReplica is a helper method to define mock.On call
//   - ctx context.Context
//   - replicaID string
func (_e *MockClusterClient_Expecter) DeleteReplica(ctx interface{}, replicaID interface{}) *MockClusterClient_DeleteReplica_Call {
	return &MockClusterClient_DeleteReplica_Call{Call: _e.mock.On("DeleteReplica", ctx, replicaID)}
}

func (_c *MockClusterClient_DeleteReplica_Call) Run(run func(ctx context.Context, replicaID string)) *MockClusterClient_DeleteReplica_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterClient_DeleteReplica_Call) Return(_a0 error) *MockClusterClient_DeleteReplica_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterClient_DeleteReplica_Call) RunAndReturn(run func(context.Context, string) error) *MockClusterClient_DeleteReplica_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplicaStatus provides a mock function with given fields: ctx, replicaID
func (_m *MockClusterClient) GetReplicaStatus(ctx context.Context, replicaID string) (model.ReplicaStatus, error) {
	ret := _m.Called(ctx, replicaID)

	if len(ret) == 0 {
		panic("no return value specified for GetReplicaStatus")
	}

	var r0 model.ReplicaStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.ReplicaStatus, error)); ok {
		return rf(ctx, replicaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.ReplicaStatus); ok {
		r0 = rf(ctx, replicaID)
	} else {
		r0 = ret.Get(0).(model.ReplicaStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, replicaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterClient_GetReplicaStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplicaStatus'
type MockClusterClient_GetReplicaStatus_Call struct {
	*mock.Call
}

// GetReplicaStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - replicaID string
func (_e *MockClusterClient_Expecter) GetReplicaStatus(ctx interface{}, replicaID interface{}) *MockClusterClient_GetReplicaStatus_Call {
	return &MockClusterClient_GetReplicaStatus_Call{Call: _e.mock.On("GetReplicaStatus", ctx, replicaID)}
}

func (_c *MockClusterClient_GetReplicaStatus_Call) Run(run func(ctx context.Context, replicaID string)) *MockClusterClient_GetReplicaStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterClient_GetReplicaStatus_Call) Return(_a0 model.ReplicaStatus, _a1 error) *MockClusterClient_GetReplicaStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterClient_GetReplicaStatus_Call) RunAndReturn(run func(context.Context, string) (model.ReplicaStatus, error)) *MockClusterClient_GetReplicaStatus_Call {
	_c.Call.Return(run)
	return _c
}

// LabelReplica provides a mock function with given fields: ctx, replicaID, labels
func (_m *MockClusterClient) LabelReplica(ctx context.Context, replicaID string, labels map[string]string) error {
	ret := _m.Called(ctx, replicaID, labels)

	if len(ret) == 0 {
		panic("no return value specified for LabelReplica")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) error); ok {
		r0 = rf(ctx, replicaID, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterClient_LabelReplica_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LabelReplica'
type MockClusterClient_LabelReplica_Call struct {
	*mock.Call
}

// LabelReplica is a helper method to define mock.On call
//   - ctx context.Context
//   - replicaID string
//   - labels map[string]string
func (_e *MockClusterClient_Expecter) LabelReplica(ctx interface{}, replicaID interface{}, labels interface{}) *MockClusterClient_LabelReplica_Call {
	return &MockClusterClient_LabelReplica_Call{Call: _e.mock.On("LabelReplica", ctx, replicaID, labels)}
}

func (_c *MockClusterClient_LabelReplica_Call) Run(run func(ctx context.Context, replicaID string, labels map[string]string)) *MockClusterClient_LabelReplica_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockClusterClient_LabelReplica_Call) Return(_a0 error) *MockClusterClient_LabelReplica_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterClient_LabelReplica_Call) RunAndReturn(run func(context.Context, string, map[string]string) error) *MockClusterClient_LabelReplica_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClusterClient creates a new instance of MockClusterClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterClient {
	mock := &MockClusterClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
